# Generated by Django 3.2.16 on 2022-10-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_tag_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='tagsubject',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
