# Generated by Django 3.2.16 on 2022-10-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20221005_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
