# Generated by Django 3.2.16 on 2022-10-05 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='tags', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='tags', to='blog.tagsubject'),
        ),
    ]
